import React from 'react';

const Noop: React.FC<any> = (props) => <>{props.children ?? null}</>;
const Icon: React.FC<any> = () => <span />;

type AnyObj = Record<string, any>;
const proxyFn = () => undefined;
const proxyObj: AnyObj = new Proxy({}, { get: () => proxyFn });

export const Textarea = (props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) => <textarea {...props} />;

export const RiAddCircleLine = Icon;
export const RiAiAgentLine = Icon;
export const RiAttachment2 = Icon;
export const RiCloseLine = Icon;
export const RiCommandLine = Icon;
export const RiExternalLinkLine = Icon;
export const RiFolderLine = Icon;
export const RiFullscreenLine = Icon;
export const RiGitPullRequestLine = Icon;
export const RiShieldCheckLine = Icon;
export const RiShieldUserLine = Icon;
export const RiGithubLine = Icon;
export const RiSendPlane2Line = Icon;
export const StopIcon = Icon;

export const BrowserVoiceButton = Noop;
export const AttachedFilesList = Noop;
export const AttachedVSCodeFileChips = Noop;
export const ActiveEditorFileSuggestion = Noop;
export const QueuedMessageChips = Noop;
export const FileMentionAutocomplete = React.forwardRef<any, any>((props, _ref) => <Noop {...props} />);
export const CommandAutocomplete = React.forwardRef<any, any>((props, _ref) => <Noop {...props} />);
export const SkillAutocomplete = React.forwardRef<any, any>((props, _ref) => <Noop {...props} />);
export const ModelControls = Noop;
export const StatusRow = Noop;
export const PendingChangesBar = Noop;
export const MobileAgentButton = Noop;
export const MobileModelButton = Noop;
export const MobileSessionStatusBar = Noop;
export const Tooltip = Noop;
export const TooltipContent = Noop;
export const TooltipTrigger = Noop;
export const DropdownMenu = Noop;
export const DropdownMenuContent = Noop;
export const DropdownMenuItem = Noop;
export const DropdownMenuTrigger = Noop;
export const Select = Noop;
export const SelectContent = Noop;
export const SelectGroup = Noop;
export const SelectItem = Noop;
export const SelectLabel = Noop;
export const SelectSeparator = Noop;
export const SelectTrigger = Noop;
export const SelectValue = Noop;
export const GitHubIssuePickerDialog = Noop;
export const GitHubPrPickerDialog = Noop;

export type QueuedMessage = AnyObj;
export type AttachedFile = AnyObj;
export type InlineCommentDraft = AnyObj;
export type FileMentionHandle = AnyObj;
export type CommandAutocompleteHandle = AnyObj;
export type SkillAutocompleteHandle = AnyObj;
export type CommandInfo = AnyObj;
export type MobileControlsPanel = any;

const createStoreHook = <T,>(state: T) => {
  const hook: any = (selector?: (s: T) => any) => (typeof selector === 'function' ? selector(state) : state);
  hook.getState = () => state;
  return hook;
};
export const useConfigStore: any = createStoreHook({ model: 'opencode-go/deepseek-v4-flash' });
export const useUIStore: any = createStoreHook({});
export const useMessageQueueStore: any = createStoreHook({ queue: [], enqueue: () => undefined, dequeue: () => undefined, clear: () => undefined });
export const useSessionUIStore: any = createStoreHook({ currentSessionId: null });
export const useSelectionStore: any = createStoreHook({ selectedText: '' });
export const useInputStore: any = createStoreHook({});
export const useUserMessageHistory: any = () => [];
export const useInlineCommentDraftStore: any = createStoreHook({});
export const useCurrentSessionActivity: any = () => ({ isRunning: false, canAbort: false });
export const useThemeSystem: any = () => ({ currentTheme: { colors: { surface: { foreground: '#dbe7ff' } } } });
export const useChatSearchDirectory: any = () => ({ directory: '', setDirectory: () => undefined });
export const useProjectsStore: any = createStoreHook({ projects: [] });
export const useGitBranches: any = () => [];
export const useGitStore: any = createStoreHook({});
export const useIsGitRepo: any = () => false;
export const useDirectoryStore: any = createStoreHook({ directory: '' });
export const useRuntimeAPIs: any = () => ({});
export const usePermissionStore: any = createStoreHook({});
export const useI18n: any = () => ({ t: (k: string) => k });

export const sessionActions: any = new Proxy({}, { get: () => async () => undefined });
export const appendInlineComments = (text: string) => text;
export const renderMagicPrompt = (text: string) => text;
export const parseAgentMentions = () => [];
export const cn = (...v: any[]) => v.filter(Boolean).join(' ');
export const formatDirectoryName = (p?: string) => p ?? '';
export const isMacOS = false;
export const toast: any = { success: () => undefined, error: () => undefined, message: () => undefined };
export const isTauriShell = false;
export const isVSCodeRuntime = false;
export const isIMECompositionEvent = () => false;
export const getCycledPrimaryAgentName = () => 'agent';
export const opencodeClient: any = proxyObj;
export const PROJECT_COLOR_MAP: Record<string, string> = {};
export const PROJECT_ICON_MAP: Record<string, string> = {};
export const getProjectIconImageUrl = () => '';
export const createWorktreeDraft = () => ({});
export const buildSessionTargetOptions = () => [];
export const extractGitChangedFiles = () => [];
export const fetchResponseStyleInstruction = async () => '';
export const getSyncMessages = () => [] as Array<{ role: string }>;
export const getCurrentWebviewWindow = () => ({ setFocus: async () => undefined });
export const invoke = async (..._args: any[]) => undefined;
